apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: balbertus
  name: balbertus
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /balbertus
      name: first-emptydir 
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: first-emptydir
    emptyDir:
      sizeLimit: "256Mi"
status: {}
