apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: balbertus
  name: balbertus
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - "200"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
