apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: balbertus2-pvc
      mountPath: /usr/share/nginx/html
  volumes:
   - name: balbertus2-pvc
     persistentVolumeClaim:
       claimName: balbertus2-pvc
