apiVersion: v1
kind: PersistentVolume
metadata:
  name:  balbertus2-pv-nfs
  labels: 
    type: nfs
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.18
    path: "/mnt/nfs/data"
  storageClassName: nfs
