apiVersion: v1
kind: PersistentVolume
metadata:
  name:  balbertus3-pv-nfsr
  labels: 
    type: nfs
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.18
    path: "/mnt/nfs/data"
  storageClassName: nfs-rancher
