apiVersion: v1
kind: PersistentVolume
metadata:
  name:  balbertus-pv
  labels: 
    type: local
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
  storageClassName: balbertus-2
