apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  balbertus-pvc-nfs
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      storage: nfs
