apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  balbertus2-pvc
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: balbertus-2
  selector:
    matchLabels:
      storage: balbertus-2
