apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-rancher
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false" 
