apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-readiness-tcp
  name: nginx-readiness-tcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-readiness-tcp
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-readiness-tcp
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: 1
            memory: "256Mi"
          requests:  
            cpu: 0.5
            memory: "128Mi"
        livenessProbe: 
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe: 
          exec:
            command: 
            - curl
            - f
            - http://localhost:80/  
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1