apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-balbertus
  name: nginx-balbertus
spec:
  replicas: 6
  selector:
    matchLabels: 
      app: nginx-balbertus
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: nginx-balbertus
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.3"
            memory: "64Mi"