apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRo
    IjogIlltRnNZbVZ5ZEhWek9tUmphM0pmY0dGMFgwaDVhR3RtZEhGQ01VRnhjMnQzYTNCNlYweDZN
    amRWZGtJelJRPT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvYWNjZXNzLXRv
    a2VuIjogewoJCQkiYXV0aCI6ICJZbUZzWW1WeWRIVnpPbVY1U21oaVIyTnBUMmxLVTFWNlNURk9h
    VWx6U1c1U05XTkRTVFpKYTNCWVZrTkpjMGx0ZEhCYVEwazJTVzVvV1dFelFrTmtSRTU1VmpOTmVW
    SjVNVEZaYW14elkwVndibU5UU2prdVpYbEtiMlJJVW5kamVtOTJUREpvTVZscE5XdGlNazV5V2xo
    SmRWa3lPWFJKYW5BM1NXMVdkRmxYYkhOSmFtOXBXVzVLTVdKdE9IVlpiVVp6V1cxV2VXUklWbnBS
    UjJSMFdWZHNjMHh0VG5aaVUwbHpTVzVPYkdNelRuQmlNalZtWVZkUmFVOXBTVFJhYlZVMVRVZEth
    MDlETVdwUFIxVTFURlJTYlU1cVJYUlpha1V3V1drd2VFNTZRVEJQUkVKb1QwUlJlRTU2WTJsTVEw
    cDZZak5XZVZreVZXbFBhVXB1WVZoU2IyUlhTV2xNUTBveFl6SldlV0p0Um5SYVUwazJTVzFLYUdK
    SFNteGpibEl4WTNsSmMwbHVWakZoVjFGcFQybEtiRnBYVFRWYVJGVjZUME13ZDAxcWJHbE1WRkpw
    V2xSSmRFOUVaekpQUXpCNVRqSldhRTFYVm14TmJVWnJUbFJqYVdaVGQybGhXRTU2U1dwdmFXRklV
    akJqU0UwMlRIazVjMkl5WkhCaWFUVnJZakpPY2xwWVNYVlpNamwwVEhsSmMwbHVUakZaYVVrMlNX
    MUdNV1JIWjNkbVIxWnNXWHBzYTA1VVRUUk1WRUY1VDFkSmRFNUhTbXhOYVRBMFQwUlpORXhVU1RO
    YVYwVjRXbGRWZVZsWFVURk9lVWx6U1cxR01WcERTVFpYZVVwdlpFaFNkMk42YjNaTU1tZ3hXV2sx
    YTJJeVRuSmFXRWwxV1RJNWRFbHBkMmxoU0ZJd1kwaE5Oa3g1T1d0aU1rNXlXbGhKZEdOSVNuWmFR
    elV4WTNrMWFHUllVbTlOUXpWcVlqSXdkbVJZVG14amJXeDFXbTA0YVZoVGQybGhWMFl3U1dwdmVF
    NTZXVEpPVkVFMVRucE5NMHhEU214bFNFRnBUMnBGTTA1cVdURk5WRTE2VFhwamMwbHVUbXBpTTBK
    c1NXcHZhV0l6UW14aWJXeHJTVWM1YlZwdGVIQmliVlptV1ZkT2FscFlUbnBKYVhkcFdWaHdkMGxx
    YjJsVVJGSXlUVWRTZEdKRk5VTmpSbXhXWVd0a1NGbFhTWGRSZWtwTFpFZGtWVm94YUhsTlZrWTJU
    a2RSYVdaUkxtOUJiWHBKYm05bllrSm1WeTAxYldSRFZVVk1NV2M1V1VOVlRFRTJXbE41Y0V0UGRs
    cEdNV2x4TFVOQmRqVlJOMW81VWtSVVFrOHlSV1ozVVU5b1IzY3hRVnBXVURSb1NtWlBaVzFXVGtw
    aWVqZ3dkV1p6VWpSb1VGZEhiRGx0VGxwcmFXcFZWV1pVVGpWblZFaHZTWEY0WVY5d04xcGlkRkZo
    YlZCVFNrcHBUM3A0WWpOSlRYWmtTM2hhTmxabVpYQjRjek4zYkRabmVURmhkMW8xTm1GMlZGQlFl
    VWRuVEc4emIzZEhUQzFJVW1sVE1VcDNZMHhLUVdwTGVraFhNMDlpZFdSUVdITlBNMjVwTjNwQllY
    QlBaVXR2V2tKdlQyTXdZbkZYT1RKUk9YVlNkbGt0WVZVdGRWQnlhVWt0ZEdoSVFXbEdkbXM1T1ZW
    MGFWbG5jV2czUldSdWVFdEhibXRTTjFCZlQwUlJiR2x1TnpjeGFWa3hVSGxHTTI5dVJrbzVWVXBr
    V0VGbGNIRnJUSFZuUm13eVVrRnhUM056Ym5rNGJHWkNRMnROZVZGb05EWm1aM1p0WkdvNFdEbFph
    RVpLTTFkRlFRPT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvcmVmcmVzaC10
    b2tlbiI6IHsKCQkJImF1dGgiOiAiWW1Gc1ltVnlkSFZ6T25ZeExrMWxVa1oyWm5wblFXaFFaakZw
    ZFVaRVZuRTFkRkJ3VkVscVVUbG9aVFpGUm5kU1IwbDFOVU40YVVwSloyMHdjekpYWW0xcGJFczFT
    V0ZhYldKTVMzTTNTV2QxZFUxVVkwTjFjMEZTV1RoNWJYTkhOemhxYXk0dVREUjJNR1J0YkU1Q2NG
    bFZha2RIWVdJd1F6SktkR2RVWjFoeU1WRjZOR1E9IgoJCX0KCX0KfQ==
    