apiVersion: v1
kind: Pod
metadata:
  name: application-pod
spec:
  containers:
  - name: application-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom: 
        secretKeyRef:
          name: application-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: application-secret
          key: password

