apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None #HeadLess service don't need an IP its the reason to put None
  selector:
    app: nginx
