apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec: #Template specification
  containers:
  - name: nginx-container # container name that will be created on the Pod.
    image: nginx 
    ports:
      - containerPort: 80
        name: http
    volumeMounts: # volume that will be mounted on container
      - name: nginx-config # name of volume
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: nginx.conf 
  - name: nginx-exporter
    image: 'nginx/nginx-prometheus-exporter:0.11.0' #image specific to nginx exporter
    args: 
      - '-nginx.scrape-uri=http://localhost/metrics' # argument to define URI scrapping   
    resources:
      limits:
        memory: 128Mi
        cpu: 0.3
    ports:
      - containerPort: 9113 #port to be exposed
        name: metrics
  volumes:
    - configMap:
        defaultMode: 420 #default mode of volume
        name: nginx-config
      name: nginx-config     