apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-podmonitor
  labels:
    app: nginx-pod
spec:
  namespaceSelector: #to select namespaces to be monitored
    matchNames:
      - default
  selector:
    matchLabels:
      app: nginx-pod
  podMetricsEndpoints: # to define which Endpoints will be monitored.
    - interval: 10s
      path: /metrics
      targetPort: 9113