apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector: #Selector to identify pods/deployment which this service will expose
    app: nginx
  ports:
  - port: 9113
    name: metrics